steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-app/image:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-app/image:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'devops-app', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-app/image:$SHORT_SHA', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/devops-app/image:$SHORT_SHA'
