name: Performance Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t devops-app:test .

    - name: Run app in Docker
      run: |
        docker run -d -p 8080:8080 --name app-container devops-app:test
        sleep 5  # Wait for app to start

    - name: Run Locust performance tests
      run: |
        cat > locustfile.py << EOL
from locust import HttpUser, task, between

class WebsiteUser(HttpUser):
    wait_time = between(1, 3)
    
    @task
    def index_page(self):
        self.client.get("/")
    
    @task
    def health_check(self):
        self.client.get("/health")
EOL
        locust --host=http://localhost:8080 --users 50 --spawn-rate 5 --run-time 1m --headless --only-summary

    - name: Stop Docker container
      run: docker stop app-container
