name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        pip install -r requirements.txt

    - name: Scan dependencies with Safety
      run: safety check -r requirements.txt

    - name: Scan code with Bandit
      run: bandit -r src/ -f json -o bandit-results.json

    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: security-scan-results
        path: bandit-results.json
